//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.23 at 08:31:50 PM EEST 
//


package shop.entity;

import java.util.ArrayList;
import java.util.List;

public class ProductList {

    protected List<Product> product;

    public ProductList() {
        super();
    }

    public ProductList(List<Product> product) {
        super();
        this.product = product;
    }

    public List<Product> getProduct() {
        if (product == null) {
            product = new ArrayList<Product>();
        }
        return this.product;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("ProductList [product=");
        builder.append(product);
        builder.append("]");
        return builder.toString();
    }

}
